In [23]:
import numpy as np

#1D data Array


In [24]:
data_1d=np.array([1,2,3,4,5])

#2D Data Array

In [25]:
data_2d=np.array([[1,2,3],[4,5,6]])

#Shape view 

In [26]:
print(data_1d.shape)

(5,)


In [27]:
print(data_2d.shape)

(2, 3)


#Reshape Array Data ROW to COLUMN


In [28]:
#data reshape
reshape_data =data_2d.reshape(3,2)

#@print
reshape_data

array([[1, 2],
       [3, 4],
       [5, 6]])

#Dimenshan view 

In [29]:
print(data_2d.ndim)


2


# Indexing and Scilising

In [30]:
print(data_1d[1])

2


In [31]:
print(data_2d[1,2])

6


In [32]:
data_1d

array([1, 2, 3, 4, 5])

In [33]:
#scilicing
print(data_1d[ :3])

[1 2 3]


In [34]:
data_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
print(data_2d[ :,1:])

[[2 3]
 [5 6]]


In [36]:
# array operation in numpy

a=np.array([1,2,3])
b=np.array([4,5,6])

In [37]:
addition=a+b
print (addition)

[5 7 9]


In [38]:
multy=a*b
print(multy)

[ 4 10 18]


In [41]:
exp_a=np.exp(a)
exp_a

array([ 2.71828183,  7.3890561 , 20.08553692])

In [42]:
log_a=np.log(a)
log_a

array([0.        , 0.69314718, 1.09861229])

In [43]:
#boardcasting with scalar
a=np.array([1,2,3])
b=10
c=a+b
c

array([11, 12, 13])

arrray aggeragation

In [46]:
data=np.array([[1,3,4],[6,7,8]])

In [49]:
tptal_sum=np.sum(data)
tptal_sum

np.int64(29)